# Source: https://gist.github.com/garethrees/5591027
- name: Set timezone variables for {{ timezone }}
  copy: content='{{ timezone }}'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644

- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

